---
- name: Install using official repo
  hosts: all
  vars_files:
    - ../vars/container.yml
    - ../vars/spec_vars.yml
  vars:
    all_gocker_images: "{{ docker_images + spec_images if spec_images is defined else docker_images }}"
  tasks:
    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present
      become: true

    - name: set user {{ ansible_facts['env']['LOGNAME'] }} to docker group
      user: 
        name: "{{ ansible_facts['env']['LOGNAME'] }}"
        groups: docker
        append: true
      become: true

    - name: pull needed containers
      community.docker.docker_image_pull:
        name: "{{ image }}"
        platform: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else ansible_facts['architecture'] }}"
      loop: "{{ all_gocker_images }}"
      loop_control:
        loop_var: "image"
      become: true
