---
- hosts: all
  name: "manage git repos local"
  become: true
  vars_files:
    - ../vars/files.yml
    - ../vars/spec_vars.yml
  vars:
    all_dirs: "{{ dirs + spec_dirs if spec_dirs is defined else dirs }}"
    all_files: "{{ files + spec_files if spec_files is defined else files }}"

  tasks:
    - name: "create required directory"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_facts['env']['LOGNAME'] }}"
        group: "{{ ansible_facts['env']['LOGNAME'] }}"
        mode: "755"
      loop: "{{all_dirs}}"

    - name: "create required files"
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        owner: "{{ ansible_facts['env']['LOGNAME'] }}"
        group: "{{ ansible_facts['env']['LOGNAME'] }}"
        mode: "775"
      loop: "{{ all_files }}"

    - name: "put files content"
      lineinfile:
        path: "{{ item.path }}"        
        line: "{{ item.content }}"
      loop: "{{ all_files }}"
      
